name: gophermart-test

services:
  postgres-test:
    image: postgres:16
    environment:
      POSTGRES_USER: gophermart_test
      POSTGRES_PASSWORD: gophermart_test
      POSTGRES_DB: gophermart_test
    ports:
      - "${POSTGRES_TEST_PORT:-5433}:5432"
